name: Feature Request
description: Suggest a new feature or improvement for the mod.
title: "[Feature Request]: "
labels: [feature-request]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the details below.
  - type: textarea
    id: feature_description
    attributes:
      label: Describe the Feature
      description: Provide a detailed description of the feature or improvement.
      placeholder: Describe your idea in detail...
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: Benefit of the Feature
      description: How will this feature improve the mod or enhance the gameplay?
      placeholder: Explain the benefits...
    validations:
      required: true