name: Localization Submission
description: Contribute a new language or update an existing one for the mod.
title: "[Localization]: "
labels: [localization]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to the mod's localization! Your help makes the mod more accessible to players around the world.
  - type: input
    id: language_name
    attributes:
      label: Language Name
      description: Please specify the name of the language you are providing or updating.
      placeholder: e.g., French, Spanish, Chinese...
    validations:
      required: true
  - type: textarea
    id: localization_content
    attributes:
      label: Localization Content
      description: Please provide the translated content here. Ensure it matches the structure provided below.
      placeholder: |
        Common: Translation Here
        Uncommon: Translation Here
        Rare: Translation Here
        Epic: Translation Here
        Legendary: Translation Here
        Mythic: Translation Here
    validations:
      required: true
  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: If there's anything else you'd like to mention about this localization, please write it here.
      placeholder: Any additional context or notes...
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution! Your localization will be reviewed and, if everything is in order, it will be included in the next update of the mod.